a. Create a null vector of size 10 but the fifth value which is 1

In [1]:
import numpy as np

In [2]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


b. Create a vector with values ranging from 10 to 49

In [3]:
b = np.arange(10,50)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


c. Reverse a vector (first element becomes last)

In [4]:
c = b[::-1]
print(c)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


d. Create a 3x3 matrix with values ranging from 0 to 8

In [5]:
d = np.arange(0,9).reshape(3,3)
print(d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


e. Find indices of non-zero elements from [1,2,0,0,4,0]

In [6]:
e = np.array([1,2,0,0,4,0])
print(np.nonzero(e))
#or
print(np.where(e != 0))

(array([0, 1, 4]),)
(array([0, 1, 4]),)


f. Create a random vector of size 30 and find the mean value

In [7]:
f = np.random.random(30)
print(np.mean(f))

0.5043729020907316


g. Create a 2d array with 1 on the border and 0 inside

In [8]:
g1 = np.array([0,0,0,0])
g2 = np.array([1,0,0,1])
g3 = g1[:,np.newaxis]+g2
g3[0][:] = 1
g3[-1][:] = 1
print(g3)

[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


h. Create a 8x8 matrix and fill it with a checkerboard pattern

In [9]:
h = np.zeros(64).reshape(8,8)
h[0::2,1::2] = 1
h[1::2,::2] = 1

print(h)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


i. Create a checkerboard 8x8 matrix using the tile function

In [10]:
i = np.array([[0,1],[1,0]])

print(np.tile(i,(4,4)))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


j. Given a 1D array, negate all elements which are between 3 and 8, in place

In [11]:
Z = np.arange(11)
print(Z)
j1 = Z < 3
j2 = Z > 8

print(Z[j1+j2])

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  9 10]


k. Create a random vector of size 10 and sort it

In [12]:
k = np.random.random(10)
print(k)
k = np.sort(k)
print(k)

[0.23555194 0.64039281 0.19409949 0.68971783 0.8598198  0.07563923
 0.94029039 0.008826   0.19725806 0.47294872]
[0.008826   0.07563923 0.19409949 0.19725806 0.23555194 0.47294872
 0.64039281 0.68971783 0.8598198  0.94029039]


l. Consider two random array A and B, check if they are equal

In [13]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(A,B)
print(equal)

[1 0 0 0 0] [0 0 1 1 0]
False


m. How to convert an integer (32 bits) array into a float (32 bits) in place?

In [14]:
m = np.arange(10, dtype=np.int32)
print(m.dtype)
m = np.float32(m)
print(m.dtype)

int32
float32


n. How to get the diagonal of a dot product?

In [15]:
A = np.arange(9).reshape(3,3)
B = A + 1
C = np.dot(A,B)
print(C)
D = np.diag(C)
print("The diagonal of the dot product is ", D)

[[ 18  21  24]
 [ 54  66  78]
 [ 90 111 132]]
The diagonal of the dot product is  [ 18  66 132]
